#!/usr/bin/env bash

# source ./scripts/functions
source ./scripts/utils

# ingress-nginx
# specify version <4.5.0 for consistency with k8s version v1.22.5
kustomize build --enable-helm ingress-nginx | kubectl -n ingress-nginx apply -f -
# wait for the ingress admission to be ready before proceeding,
# otherwise deployment of other BBs will fail
ingress_admission_ready_check

# identity-service (Keycloak)
kustomize build --enable-helm identity-service | kubectl -n um apply -f -

# the identity-api is protected by a gatekeeper instance that relies upon
# a Keycloak client that must be created
createIdentityApiClient

# create test users - e.g. those assumed by the Application Hub
users=("eric" "bob" "alice")
for user in "${users[@]}"; do
  createUser "${user}"
done

# application-hub
kustomize build --enable-helm application-hub | kubectl -n app-hub apply -f -

# the application-hub integrates with Keycloak via OIDC for user authentication
# this relies upon a Keycloak client that must be created
./scripts/create-client \
  -a http://keycloak.192-168-49-2.nip.io \
  -i http://identity-api.192-168-49-2.nip.io \
  -r master \
  -u admin \
  -p changeme \
  -c admin-cli \
  --id=application-hub \
  --name="Application Hub OIDC Client" \
  --secret=changeme \
  --description="Client to be used by Application Hub for OIDC integration"
