resources:
  - namespace.yaml

generators:
  - secret.yaml

helmCharts:
  - name: application-hub
    repo: https://eoepca.github.io/helm-charts
    version: 2.0.57
    releaseName: application-hub
    namespace: app-hub
    skipTests: true
    valuesInline:
      ingress:
        enabled: true
        annotations: {}
        hosts:
          - host: applicationhub.192-168-49-2.nip.io
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
          - secretName: applicationhub-tls
            hosts:
            - applicationhub.192-168-49-2.nip.io
        clusterIssuer: notls

      jupyterhub:
        fullnameOverride: "application-hub"
        hub:
          existingSecret: application-hub-secrets
          extraEnv: 
              JUPYTERHUB_ENV: "dev"
              JUPYTERHUB_SINGLE_USER_IMAGE: "eoepca/pde-container:1.0.3"
              OAUTH_CALLBACK_URL: http://applicationhub.192-168-49-2.nip.io/hub/oauth_callback
              OAUTH2_USERDATA_URL: http://keycloak.192-168-49-2.nip.io/realms/master/protocol/openid-connect/userinfo
              OAUTH2_TOKEN_URL: http://keycloak.192-168-49-2.nip.io/realms/master/protocol/openid-connect/token
              OAUTH2_AUTHORIZE_URL: http://keycloak.192-168-49-2.nip.io/realms/master/protocol/openid-connect/auth
              OAUTH_LOGOUT_REDIRECT_URL: "http://applicationhub.192-168-49-2.nip.io"
              OAUTH2_USERNAME_KEY: "preferred_username"
              STORAGE_CLASS: standard
              RESOURCE_MANAGER_WORKSPACE_PREFIX: "ws"

              JUPYTERHUB_CRYPT_KEY:
                valueFrom:
                  secretKeyRef:
                    name: application-hub-secrets
                    key: JUPYTERHUB_CRYPT_KEY

              OAUTH_CLIENT_ID:
                valueFrom:
                  secretKeyRef:
                    name: application-hub-secrets
                    key: OAUTH_CLIENT_ID
                
              OAUTH_CLIENT_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: application-hub-secrets
                    key: OAUTH_CLIENT_SECRET

          image:
            # name: eoepca/application-hub
            # tag: "1.2.0"
            pullPolicy: Always
            # pullSecrets: []

          db:
            pvc:
              storageClassName: 
        
        singleuser:
          image:
            name: jupyter/minimal-notebook
            tag: "2343e33dec46"
          profileList: 
          - display_name:  "Minimal environment"
            description: "To avoid too much bells and whistles: Python."
            default: "True"
          - display_name:  "EOEPCA profile"
            description: "Sample profile"
            kubespawner_override:
              cpu_limit": 4
              mem_limit": "8G"

      nodeSelector:
        key: minikube.k8s.io/primary
        value: \"true\"
