resources:
  - namespace.yaml

helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: "<4.5.0"
    releaseName: ingress-nginx
    namespace: ingress-nginx
    skipTests: true
    valuesInline:
      controller:
        config:
          ssl-redirect: false
        watchIngressWithoutClass: true
        ingressClassResource:
          default: true
        service:
          externalIPs:
            - 192.168.49.2
        publishService:
          enabled: false
