resources:
  - namespace.yaml

generators:
  - secret.yaml

helmCharts:
  - name: minio
    repo: https://charts.min.io/
    releaseName: minio
    namespace: rm
    skipTests: true
    valuesInline:
      existingSecret: minio-auth
      replicas: 2

      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: notls
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
        path: /
        hosts:
          - minio.192-168-49-2.nip.io
        tls:
          - secretName: minio-tls
            hosts:
              - minio.192-168-49-2.nip.io

      consoleIngress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: notls
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
        path: /
        hosts:
          - console.minio.192-168-49-2.nip.io
        tls:
        - secretName: minio-console-tls
          hosts:
            - console.minio.192-168-49-2.nip.io

      resources:
        requests:
          memory: 1Gi

      persistence:
        storageClass: standard

      buckets:
        - name: eoepca
        - name: cache-bucket
